ALTER TABLE inventory_endpoint
ADD COLUMN IF NOT EXISTS custom_field_1_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_2_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_3_value TEXT NOT NULL DEFAULT '';

ALTER TABLE app_settings
ADD COLUMN IF NOT EXISTS custom_field_1_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_1_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_2_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_2_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_3_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_3_name TEXT NOT NULL DEFAULT '';
