ALTER TABLE inventory_endpoint
ADD COLUMN IF NOT EXISTS gateway INET,
ADD COLUMN IF NOT EXISTS mgmt_ip INET,
ADD COLUMN IF NOT EXISTS speed TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS duplex TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_4_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_5_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_6_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_7_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_8_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_9_value TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_10_value TEXT NOT NULL DEFAULT '';

ALTER TABLE app_settings
ADD COLUMN IF NOT EXISTS custom_field_4_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_4_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_5_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_5_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_6_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_6_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_7_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_7_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_8_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_8_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_9_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_9_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS custom_field_10_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custom_field_10_name TEXT NOT NULL DEFAULT '';
